### ISSUE TITLE
Can't find key

### ISSUE THREAD

**Issue by turrnut** [aarikpokras/ebsl#15]
### Bug summary

It says it can't find a key even though the key exists

### OS

Windows 11

### Step of use

Runtime

### Steps to reproduce

So I have a file called `test.ebsl` with content as follows:
```ebsl
key=value1,value2
key2=value3,value4
key3=value5,value6
```
When I run
```
build\ebsl.exe file=test.ebsl amt=2 key=key2
```
it prints
```
Error: the specified key key2 does not exist
```
However when I run:
```
build\ebsl.exe file=test.ebsl key=key amt=2
```
it works just fine

### Expected behavior

It is suppose to recognize `key2` as one of the keys

### Screenshots

![GITHUBISSUE](https://github.com/user-attachments/assets/6572df47-6c57-41d6-81d6-7eb7174b528e)

**Comment by aarikpokras** [comment]
That's so strange. I'm looking into this now. @turrnut, can you clarify what version this is?

**Comment by aarikpokras** [comment]
@turrnut, I believe I found the problem. It's the else statement checking if there isn't a regex match for the key. I got rid of it and plan to upload it soon. In the interim, I believe the release v2.2.0 works fine, except with amt, you need to add one to the amount. For example:
```console
./ebsl file=file key=key amt=2
# This will print 1 key
```
This will be fixed soon.

**Comment by aarikpokras** [comment]
@turrnut, this major bug is removed at the price of a smaller one, where it throws an abort trap when the key isn't found. I'll keep this and work on a way to fix it.

**Comment by aarikpokras** [comment]
Hi @turrnut, I fixed it! Thank you for telling me this!
