### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by turrnut** [aarikpokras/ebsl#2]
So I downloaded the code and did `cmake -Bbuild` on the root directory
but then I got the following error:
```
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```
What might be the reason that this happens?

**Comment by aarikpokras** [comment]
Sorry about that, @turrnut, it seems like cmake requires additional options on other systems. Can you please specify what OS and machine you are on?
In the interim, try meson and tell me if that works.

**Comment by turrnut** [comment]
Of course! I am on Windows 11.

**Comment by aarikpokras** [comment]
@turrnut Okay, I'm not very familiar with Windows CMake, because it's less universal, as opposed to systems like Meson. Do you think you could try doing it the Meson way and then tell me if it works?
Thank you and sorry about this. I wrote the program on Linux.

**Comment by aarikpokras** [comment]
@turrnut, do you think you could try it with Meson?

**Comment by turrnut** [comment]
@aarikpokras Meson worked. Thanks!

**Comment by aarikpokras** [comment]
Of course! I'm glad it worked. Thank you!

**Comment by aarikpokras** [comment]
@turrnut I believe this is because the `nmake` command is not installed on your computer (I guess for some reason it's not installed natively on any windows machine 🤷). If you have Visual Studio Code, you can install the CMake tools extension as nmake comes with this. Otherwise, I believe you might be able to use WinGet.

**Comment by turrnut** [comment]
@aarikpokras I installed CMake tools extension in VSCode, but I do not have `nmake`.
also, it seems like I don't have `winget` on my system for some reason. Is there another way to install `nmake`?

**Comment by aarikpokras** [comment]
@turrnut, you could also try to look for it in the native app installer. I would recommend looking for `nmake` itself or CMake.

**Comment by aarikpokras** [comment]
@turrnut, sorry about this. It seems that in VSC, you can install C++ Build tools and nmake should be included with this.

Here are some things you can refer to:
https://stackoverflow.com/a/78311221/21266386
https://stackoverflow.com/questions/40504552/how-to-install-visual-c-build-tools

**Comment by turrnut** [comment]
@aarikpokras I have the C++ Build Tools installed but it doesn't seem to work.

**Comment by aarikpokras** [comment]
@turrnut, here's an alternative using a different makefile generator. Please tell me if this works.
```
cmake -G "MinGW Makefiles" build
```
or if that doesn't work, try:
```
cmake -G "MinGW Makefiles" -Bbuild
```

**Comment by turrnut** [comment]
@aarikpokras Neither command worked and it seems like there are some missing packages.
![图片](https://github.com/user-attachments/assets/97366a67-2209-418a-baed-32ffe651384e)

**Comment by aarikpokras** [comment]
@turrnut, sorry. I guess CMake is just not very good. If you're okay with it, I'd recommend just using Meson. Also, I have a new repo called [CxL](https://github.com/aarikpokras/CxL) if you'd like to check out and test it for me.

**Comment by turrnut** [comment]
@aarikpokras Yea, Meson works fine with me.
